import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './Header/header'
import NftContent from './NftContent/NftContent'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div className='Modz flex w-full'>
          <div className='Modz-left w-2/5'>
            <h1 className="filters">Bored Ape Yacht Club</h1>
            <p className='flex nft-info justify-between	text-lg	'><span>10000 TOKENS</span><span>6355 OWNERS</span><span>99 ETH FLOOR</span> </p>
          </div>
          <div className='flex w-full items-center justify-end'>
            <button type="button" className="token-list-btn text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">List Tokens</button>
          </div>
        </div>
        <NftContent />
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>

  )
}
